springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    server: http://localhost:8080
    disable-swagger-default-url: 'true'
    path: /swagger-ui.html
    oauth:
      client-id:
      client-secret: 
      additional-query-string-params:
        audience: customer
      use-basic-authentication-with-access-code-grant: 'true'
  oAuthFlow:
    authorizationUrl: https://icc-demo.eu.auth0.com/authorize
    tokenUrl: https://icc-demo.eu.auth0.com/oauth/token

spring:
  datasource:
    username: admin
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    password: nimda
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://icc-demo.eu.auth0.com/.well-known/jwks.json
          issuer-uri: https://icc-demo.eu.auth0.com/
server:
  port: '8080'
logging:
  level:
    root: TRACE


